import localFont from "next/font/local";
import Link from "next/link";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
      <ul className="flex items-center gap-3 mt-4">
        <li className="font-bold text-[24px]"><Link href="/">Home</Link></li>
        <li className="font-bold text-[24px]"><Link href="/about">About</Link></li>
      </ul>
      </nav>
      <hr/>
        {children}
      </body>
    </html>
  );
}
